# -*- coding: utf-8 -*-
from dotenv import dotenv_values
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_PATH = os.path.join(BASE_DIR, '.env')

print(f'[CONFIG] Loading .env from: {ENV_PATH}')
print(f'[CONFIG] .env exists      : {os.path.exists(ENV_PATH)}')

# Use dotenv_values() to read into a dict without setting OS env vars.
# This avoids the Windows 32767-char limit that large base64 images would exceed.
_env = dotenv_values(ENV_PATH, encoding='utf-8-sig')

BASE_URL = _env.get('BASE_URL', '').rstrip('/')
API_KEY  = _env.get('x-api-key')
TOKEN    = _env.get('TOKEN')

print(f'[CONFIG] BASE_URL         : {BASE_URL}')
print(f'[CONFIG] API_KEY loaded   : {"yes" if API_KEY else "no"}')

if not BASE_URL:
    raise EnvironmentError('BASE_URL is not set. Check your .env file at: ' + ENV_PATH)
if not API_KEY:
    raise EnvironmentError('x-api-key is not set. Check your .env file at: ' + ENV_PATH)

JOB_ID         = _env.get('JOB_ID', '').strip() or None
SCAN_DIRECTORY = _env.get('SCAN_DIRECTORY', '').strip() or None

print(f'[CONFIG] JOB_ID           : {JOB_ID if JOB_ID else "not set"}')
print(f'[CONFIG] SCAN_DIRECTORY   : {SCAN_DIRECTORY if SCAN_DIRECTORY else "not set"}')

TRACE_ID = 'pytest-facematcher'  # set to None to let the server auto-generate

HEADERS = {
    'x-api-key':    API_KEY,
    'Content-Type': 'application/json',
    **({"x-aware-trace-id": TRACE_ID} if TRACE_ID else {}),
}

print(f'[CONFIG] TRACE_ID         : {TRACE_ID if TRACE_ID else "auto-generated by server"}')

# ── Named images from .env (small set — backward compatible) ──────────────────
# These are the hand-picked images used in specific named tests (TC-D01, TC-D03, …).
# For bulk test data (200 images) use IMAGE_MANIFEST / load_manifest() below.
IMAGES = {
    'dan_face':      _env.get('IMAGE_DAN_FACE'),
    'john_face':     _env.get('IMAGE_JOHN_FACE'),
    'jane_face':     _env.get('IMAGE_JANE_FACE'),
    'part_face':     _env.get('IMAGE_PART_FACE'),
    'l_face':        _env.get('IMAGE_L_FACE'),
    'r_face':        _env.get('IMAGE_R_FACE'),
    'two_spoof':     _env.get('IMAGE_TWO_SPOOF'),
    'IMAGE_L_CHEEK': _env.get('IMAGE_L_CHEEK'),
    'IMAGE_R_CHEEK': _env.get('IMAGE_R_CHEEK'),
    'IMAGE_CHIN':    _env.get('IMAGE_CHIN'),
}

# ── Impostor image fallback ────────────────────────────────────────────────────
# john_face must be a genuinely different person from dan_face.
# If IMAGE_JOHN_FACE is unset or identical to IMAGE_DAN_FACE, scan the manifest
# and use the compare endpoint (image vs image, no gallery) to find the first
# candidate that scores < 2.0 against dan_face — confirming it is a different person.
# Tries up to MAX_IMPOSTOR_CANDIDATES images; fast path exits on the first valid hit.
_manifest_path = os.path.join(BASE_DIR, 'tests', 'data', 'images.json')
_john_needs_fallback = (
    not IMAGES.get('john_face')
    or IMAGES.get('john_face') == IMAGES.get('dan_face')
)
if _john_needs_fallback and os.path.exists(_manifest_path):
    try:
        import json as _json
        import requests as _req

        MAX_IMPOSTOR_CANDIDATES = 20  # stop after this many attempts
        IMPOSTOR_SCORE_CEILING  = 2.0  # score must be below this to be a different person

        with open(_manifest_path, encoding='utf-8') as _f:
            _manifest_images = _json.load(_f)['images']

        _probe_b64   = IMAGES.get('dan_face', '')
        _impostor    = None
        _tried       = 0

        for _candidate in _manifest_images:
            if _candidate['base64'] == _probe_b64:
                continue  # skip if somehow the exact same bytes
            _tried += 1
            _r = _req.post(
                f'{BASE_URL}/facematch/compare',
                headers=HEADERS,
                json={
                    'probe':     {'image': _probe_b64},
                    'candidate': {'image': _candidate['base64']},
                },
                timeout=10,
            )
            if _r.status_code == 200:
                _score = _r.json().get('score', 99)
                if _score < IMPOSTOR_SCORE_CEILING:
                    _impostor = _candidate
                    break
            if _tried >= MAX_IMPOSTOR_CANDIDATES:
                break

        if _impostor:
            IMAGES['john_face'] = _impostor['base64']
            print(f'[CONFIG] john_face      : validated impostor from manifest  '
                  f'(id={_impostor["id"]}  tried={_tried})')
        else:
            print(f'[CONFIG] john_face      : no valid impostor found after {_tried} attempts')
    except Exception as _e:
        print(f'[CONFIG] john_face      : fallback failed ({_e})')
elif _john_needs_fallback:
    print('[CONFIG] john_face      : missing — run scripts/generate_image_manifest.py')

for _key, _val in IMAGES.items():
    if _key != 'john_face':   # john_face already logged above with source info
        print(f'[CONFIG] {_key:<14} : {"loaded" if _val else "missing"}')

# ── Bulk image manifest (200 sampled images from tests/data/images.json) ──────
# Generated by:  python scripts/generate_image_manifest.py
# Not auto-loaded here to avoid 20 MB parse on every import.
# Tests that need bulk images should call load_manifest() directly:
#
#   from tests.data.image_loader import load_manifest
#   manifest = load_manifest()
#
IMAGE_MANIFEST_PATH = os.path.join(BASE_DIR, 'tests', 'data', 'images.json')


def ensure_gallery(name):
    """Create gallery if it doesn't exist. Returns gallery name."""
    import requests as _r
    r = _r.post(f'{BASE_URL}/facematch/galleries', headers=HEADERS, json={'name': name})
    if r.status_code == 200:
        print(f'[ensure_gallery] Created: {name}')
    elif r.status_code == 400:
        print(f'[ensure_gallery] Already exists, reusing: {name}')
    else:
        raise RuntimeError(f'[ensure_gallery] Unexpected {r.status_code}: {r.text}')
    return name
