# -*- coding: utf-8 -*-
from dotenv import dotenv_values
import os

# All config and images live in the root .env (one level up from this file)
BASE_DIR  = os.path.dirname(os.path.abspath(__file__))
ENV_PATH  = os.path.abspath(os.path.join(BASE_DIR, '..', '.env'))

print(f'[CONFIG] Loading .env from: {ENV_PATH}')
print(f'[CONFIG] .env exists      : {os.path.exists(ENV_PATH)}')

# Use dotenv_values() to read into a dict without setting OS env vars.
# This avoids the Windows 32767-char limit that large base64 images would exceed.
_env = dotenv_values(ENV_PATH, encoding='utf-8-sig')

BASE_URL = _env.get('BASE_URL', '').rstrip('/')
API_KEY  = _env.get('x-api-key')

print(f'[CONFIG] BASE_URL         : {BASE_URL}')
print(f'[CONFIG] API_KEY loaded   : {"yes" if API_KEY else "no"}')

if not BASE_URL:
    raise EnvironmentError('BASE_URL is not set. Check your .env file at: ' + ENV_PATH)
if not API_KEY:
    raise EnvironmentError('x-api-key is not set. Check your .env file at: ' + ENV_PATH)

JOB_ID   = _env.get('JOB_ID', '').strip() or None

print(f'[CONFIG] JOB_ID           : {JOB_ID if JOB_ID else "not set"}')

TRACE_ID = 'pytest-facematcher'  # set to None to let the server auto-generate

HEADERS = {
    'x-api-key':    API_KEY,
    'Content-Type': 'application/json',
    **({"x-aware-trace-id": TRACE_ID} if TRACE_ID else {}),
}

print(f'[CONFIG] TRACE_ID         : {TRACE_ID if TRACE_ID else "auto-generated by server"}')

IMAGES = {
    'dan_face':   _env.get('IMAGE_DAN_FACE'),
    'john_face':  _env.get('IMAGE_JOHN_FACE'),
    'jane_face':  _env.get('IMAGE_JANE_FACE'),
    'part_face':  _env.get('IMAGE_PART_FACE'),
    'l_face':     _env.get('IMAGE_L_FACE'),
    'r_face':     _env.get('IMAGE_R_FACE'),
    'two_spoof':  _env.get('IMAGE_TWO_SPOOF'),
}

for _key, _val in IMAGES.items():
    print(f'[CONFIG] {_key:<12} : {"loaded" if _val else "missing"}')


def ensure_gallery(name):
    """Create gallery if it doesn't exist. Returns gallery name."""
    import requests as _r
    r = _r.post(f'{BASE_URL}/facematch/galleries', headers=HEADERS, json={'name': name})
    if r.status_code == 200:
        print(f'[ensure_gallery] Created: {name}')
    elif r.status_code == 400:
        print(f'[ensure_gallery] Already exists, reusing: {name}')
    else:
        raise RuntimeError(f'[ensure_gallery] Unexpected {r.status_code}: {r.text}')
    return name